### ISSUE TITLE
https://anaconda.org/conda-forge/rbdl-casadi   doesn't work

### ISSUE THREAD

**Issue by nashmit** [pyomeca/rbdl-casadi#21]
Hi,
I am trying to make use of RBDL from python by installing: https://anaconda.org/conda-forge/rbdl-casadi however, once I am installing it: " conda install -c conda-forge rbdl-casadi " I am unable to import the project: "import rbdl"

```
import rbdl
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-93b650d5739d> in <module>
----> 1 import rbdl

ModuleNotFoundError: No module named 'rbdl'
```

Is there something wrong with this package?

Best,
Alex C.

**Comment by pariterre** [comment]
Hi! 
RBDL-CASADI is deprecated since it has been fully merged with RBDL-ORB. Therefore, for installing RBDL from conda, you just have to type: 
`conda install rbdl -cconda-forge`
That said, as far as I am concerned, the Python binder is not build. Only the C++ core is built using conda.

**Comment by nashmit** [comment]
Thanks for your fast answer! 

So, if I want to use RBDL from python I should compile it from the sources and activate the python bindings since currently, the Anaconda version doesn't have the python module active. In my experience, this works smoothly in Linux but requires extra work in windows as the CMake files were not tested under windows.

Any other workaround for having it under windows without doing extra work? 
In the end, I want to use it only for 2 calls, ( one to load a robot using URDF format and the second one to compute the forward dynamics ). The forward dynamics part is also available as part of https://github.com/pyomeca/biorbd project but I wasn't able to access the URDF plugin. I can see that you are using a proprietary format only, though according to this statement "Therefore, every functions available in RBDL is also available on BIORBD." one should also have access to the rest of the RBDL API... I think... Am I doing something wrong?

Thanks!
