### ISSUE TITLE
RBDL vs RBDL-Casadi: Issues with contact constraints and gravity

### ISSUE THREAD

**Issue by jcllau** [pyomeca/rbdl-casadi#22]
Hello!

Menna (@MennatallahRihan), Jonathan (@jfslin), and I are experiencing two issues with RBDL-Casadi.

The first issue is related to gravity. When using pure RBDL (obtained from https://github.com/ORB-HD/rbdl-orb) with gravity enabled, initial states = 0, and initial controls = 0, the simulation results show a model free-falling with no body parts rotating (we used a human model). However, when we repeat the same process with RBDL-Casadi, the model falls to one side with body parts rotating and at some point all state variables immediately become nans. We compared the model results of RBDL and RBDL-Casadi again by disabling gravity completely. The results generated from pure RBDL shows the model in default position not moving at all, but the results generated from RBDL-Casadi shows the model rotating in space.

The second issue is related to contact constraints (specifically when calling RBDL's ForwardDynamicsContactsDirect()). We want to apply contact constraints to the model's feet so that the feet are in contact with the ground. When performing free-falling using pure RBDL with gravity enabled (initial states = initial controls = 0), the contact constraints are obeyed. However, when repeating the same using RBDL-Casadi, the contact constraints were not obeyed at all, and the simulation results show the model falling through the ground to one side while rotating in space, and at some point the model flies into space in the opposite direction.

We would like to have some guidance on RBDL-Casadi because we don't know why we are seeing these results. Hope to hear from you soon!

Thanks,
Jan

**Comment by pariterre** [comment]
Hello!

The rbdl-casadi repo has long been deprecated as it is now fully integrated in the main RBDL repo (github.com/rbdl/rbdl). It is kept for backward compatilibity sake, but should not be used. I will update the readme!

 Did you install from conda or you compiled yourselves? If you compile yourselves I would suggest to compile the 3.2.0 version. If you installed from conda, you are likely to have the latest version, I would therefore need a failing code to help as casadi and eigen backends are supposed to behave the same :)

**Comment by jcllau** [comment]
Hi Benjamin! Thanks for the quick reply and also pointing us to version 3.2.0. Unfortunately, we are still facing the same issues with the newest version, and have created a new issue in that repo (https://github.com/rbdl/rbdl/issues/61)

**Comment by pariterre** [comment]
Answer over there!
